# Workflow name
name: backend-workflow

# Triggers for the workflow
on:
  # Run workflow on demand
  workflow_dispatch:
  
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
      
    paths:
      # Specify paths that should trigger the workflow
      - 'backend/**'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install pipenv and dependencies
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd backend
          pipenv install --dev  # Install all dependencies including dev dependencies

      # Run tests using pytest with Pipenv
      - name: Run tests with pytest
        run: |
          cd backend
          pipenv run pytest  # Use the pipenv environment to run pytest

      # Run lint using pipenv
      - name: Run lint with Pipenv
        run: |
          cd backend
          pipenv run lint

      # Build and Run docker image
      - run: cd backend && docker build --tag mp-backend:latest .
      - run: cd backend && docker run -p 5000:5000 --name mp-backend -d mp-backend
      
      # Check the running application
      - run: curl http://localhost:5000/movies
      
      # Review logs
      # - run: docker logs -f mp-backend
      
      # Stop the application
      - run: docker stop

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."
