# Workflow name
name: backend-workflow

# Triggers for the workflow
on:
  # Run workflow on demand
  workflow_dispatch:
  
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
      
    paths:
      # Specify paths that should trigger the workflow
      - 'frontend/**'
  
#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (specify your Python version here)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Use the Python version that you need

      # Install pipenv
      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      # Run a command (e.g., lint, test, or start the application) using pipenv
      - name: Run tests with Pipenv
        run: |
          cd backend
          pipenv run test
          pipenv run lint

      # Optional: Run the application or any other script
      # - name: Run Application
        # run: |
          # pipenv run python test_app.py