# Workflow name
name: backend-workflow

# Triggers for the workflow
on:
  # Run workflow on demand
  workflow_dispatch:
  
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
      
    paths:
      # Specify paths that should trigger the workflow
      - 'backend/**'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (specify your Python version here)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Use the Python version that you need

      # Install pipenv and dependencies
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd backend
          pipenv install --dev  # Install all dependencies including dev dependencies

      # Run tests using pytest with Pipenv
      - name: Run tests with pytest
        run: |
          cd backend
          pipenv run pytest  # Use the pipenv environment to run pytest

      # Run lint using pipenv
      - name: Run lint with Pipenv
        run: |
          cd backend
          pipenv run lint  # Ensure 'lint' is defined in Pipfile [scripts] section if needed

      # Optional: Run the application or any other script
      - name: Run Application
        run: |
          cd backend
          pipenv run python -m <module_name>  # Replace <module_name> with your main module
