name: Backend Continuous Deployment

on:
  workflow_run:
    workflows: ["Backend Continuous Integration"]
    types:
      - completed
  # Run workflow on demand
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: mp-backend-image

      - name: Load Docker image
        run: |
          docker load -i mp-backend.tar

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: backend-repo
          IMAGE_TAG: mp-backend-${{ github.run_number }}
        run: |
          docker tag mp-backend $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name movie-picture-cluster --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          cd backend/k8s
          kustomize edit set image backend=$REGISTRY/$REPOSITORY:$IMAGE_TAG
          kustomize build | kubectl apply -f -
          
      - name: Send completion message
        run: |
          echo "Deployment completed successfully."
