name: Backend Continuous Integration

on:  
  # Run workflow on demand
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd backend
          pipenv install --dev

      - name: Run tests with pytest
        run: |
          cd backend
          pipenv run pytest

      - name: Run lint with Pipenv
        run: |
          cd backend
          pipenv run lint

      - name: Build Docker image
        run: |
          cd backend
          docker build -t mp-backend .

      - name: Save Docker image as artifact
        run: |
          docker save mp-backend -o mp-backend.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: mp-backend-image
          path: backend/mp-backend.tar
