# Workflow name
name: ci-Workflow

# Triggers for the workflow
on:
  # Rub ob demand
  workflow_dispatch:
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
      
    paths:
      # Specify paths that should trigger the workflow
      - 'frontend/**'
  
#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [16.x, 18.x]
        node-version: [18.18.0]

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Init json package
        run: npm init -y

      # Install the dependencies.
      - name: Install dependencies
        run: cd frontend && npm ci
      
      # Run the tests.
      - name: Running tests
        run: cd frontend && npm test
          
      # Run the linter.
      - run: cd frontend && npm run lint
      
      REACT_APP_MOVIE_API_URL=http://localhost:5000 npm start
      
      - run: cd frontend && docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
      - run: cd frontend && docker run --name mp-frontend -p 3000:3000 -d mp-frontend


      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."